In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
pop = {'Nevada' :{2001: 2.4, 2002: 2.9},
      'Ohio':{2000: 1.5, 2001: 1.7, 2002: 3.6}}

In [5]:
pop = pd.DataFrame(pop)

In [6]:
pop

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [28]:
a = frame3['Ohio'][:-1]

In [29]:
b =frame3['Nevada'][:2]

In [21]:
frame3 = pd.DataFrame(pop)

In [30]:
frame3

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [31]:
pdata = {'Ohio': a,'Nevada': b}

In [24]:
pdata

{'Ohio': 2000    1.5
 2001    1.7
 Name: Ohio, dtype: float64, 'Nevada': 2000    NaN
 2001    2.4
 Name: Nevada, dtype: float64}

In [32]:
pdata = pd.DataFrame(pdata)

In [33]:
pdata

Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4

In [41]:
frame3.index.name = 'Year'; frame3.columns.name = 'State'

In [42]:
frame3

State  Nevada  Ohio
Year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [44]:
#for getting only values
frame3.values

array([[nan, 1.5],
       [2.4, 1.7],
       [2.9, 3.6]])

# Index Objects

In [45]:
 obj = pd.Series(range(3), index=['a', 'b', 'c'])

In [46]:
index = obj.index

In [47]:
index

Index(['a', 'b', 'c'], dtype='object')

In [50]:
index[1:]

Index(['b', 'c'], dtype='object')

In [51]:
obj[1:]

b    1
c    2
dtype: int64

In [53]:
labels = pd.Index(np.arange(3))

In [54]:
labels

Int64Index([0, 1, 2], dtype='int64')

In [55]:
obj2 = pd.Series([1.5, -2.5, 0], index=labels)

In [56]:
obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

# Reindexing

In [57]:
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index=['d', 'b', 'a', 'c'])

In [58]:
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [59]:
obj2 = obj.reindex(['a', 'b', 'c', 'd', 'e'])

In [60]:
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [63]:
obj3 = pd.Series(['blue', 'purple', 'yellow'], index=[0, 2, 4])
obj3

0      blue
2    purple
4    yellow
dtype: object

In [62]:
obj3.reindex(range(6), method='ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [64]:
obj4 = pd.Series(['blue', 'purple', 'yellow'], index=[1, 3, 5])
obj4

1      blue
3    purple
5    yellow
dtype: object

In [66]:
obj4.reindex(range(16), method='ffill')

0        NaN
1       blue
2       blue
3     purple
4     purple
5     yellow
6     yellow
7     yellow
8     yellow
9     yellow
10    yellow
11    yellow
12    yellow
13    yellow
14    yellow
15    yellow
dtype: object

In [67]:
frame = pd.DataFrame(np.arange(9).reshape((3, 3)),
        index=['a', 'c', 'd'],
        columns=['Ohio', 'Texas', 'California'])

In [68]:
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [70]:
frame = frame.reindex(['a','b','c','d'])
frame

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

# Dropping Entries from an Axis

In [71]:
 obj = pd.Series(np.arange(5.), index=['a', 'b', 'c', 'd', 'e'])

In [72]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [73]:
new_obj = obj.drop('c')

In [74]:
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [75]:
obj.drop(['d', 'c'])

a    0.0
b    1.0
e    4.0
dtype: float64

In [76]:
 data = pd.DataFrame(np.arange(16).reshape((4, 4)),
        index=['Ohio', 'Colorado', 'Utah', 'New York'],
        columns=['one', 'two', 'three', 'four'])

In [77]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [78]:
data.drop(['Colorado','Ohio'])

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [79]:
data.drop('two', axis=1)

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [80]:
obj.drop('c', inplace=True)

In [81]:
obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

# Indexing, Selection, and Filtering

In [86]:
obj = pd.Series(np.arange(4.), index=['a', 'b', 'c', 'd'])
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [84]:
obj['b']

1.0

In [85]:
obj['b':'d']

b    1.0
c    2.0
d    3.0
dtype: float64

In [87]:
obj[2:4]

c    2.0
d    3.0
dtype: float64

In [88]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
      index=['Ohio', 'Colorado', 'Utah', 'New York'],
      columns=['one', 'two', 'three', 'four'])


In [89]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [90]:
data[data['three'] > 5]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

# Selection with loc and iloc

In [91]:
data.loc['Colorado', ['two', 'three']]

two      5
three    6
Name: Colorado, dtype: int32

In [92]:
data.iloc[2, [3, 0, 1]]

four    11
one      8
two      9
Name: Utah, dtype: int32

In [93]:
data.iloc[[1, 2], [3, 0, 1]]

four  one  two
Colorado     7    4    5
Utah        11    8    9

In [94]:
data.loc[:'Utah', 'two']

Ohio        1
Colorado    5
Utah        9
Name: two, dtype: int32

In [95]:
data.iloc[:, :3][data.three > 5]

one  two  three
Colorado    4    5      6
Utah        8    9     10
New York   12   13     14

In [98]:
df1 = pd.DataFrame(np.arange(9.).reshape((3, 3)), columns=list('bcd'),
        index=['Ohio', 'Texas', 'Colorado'])
df1

b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [101]:
 df2 = pd.DataFrame(np.arange(12.).reshape((4, 3)), columns=list('bde'),
      index=['Utah', 'Ohio', 'Texas', 'Oregon']) 
df2

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [102]:
df1 + df2

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [106]:
df1 = pd.DataFrame({'A': [1, 2]})
df1

A
0  1
1  2

In [107]:
df2 = pd.DataFrame({'B': [3, 4]})
df2

B
0  3
1  4

In [108]:
df1 - df2

A   B
0 NaN NaN
1 NaN NaN

# Arithmetic methods with fill values

In [112]:
df1 = pd.DataFrame(np.arange(12.).reshape((3, 4)),
     columns=list('abcd'))
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [111]:
 df2 = pd.DataFrame(np.arange(20.).reshape((4, 5)),
      columns=list('abcde'))
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   6.0   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [113]:
df2.loc[1,'b'] = np.nan

In [114]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [115]:
df1 + df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [118]:
df1.add(df2, fill_value=1)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   5.0
1   9.0   6.0  13.0  15.0  10.0
2  18.0  20.0  22.0  24.0  15.0
3  16.0  17.0  18.0  19.0  20.0

# Operations between DataFrame and Series

In [119]:
arr = np.arange(12.).reshape((3, 4))

In [120]:
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [121]:
arr[0]

array([0., 1., 2., 3.])

In [122]:
arr - arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

# Function Application and Mapping

In [123]:
frame = pd.DataFrame(np.random.randn(4, 3), columns=list('bde'),
     index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [124]:
frame

b         d         e
Utah   -1.156886  0.651762  0.476286
Ohio   -1.461636 -1.246607  0.008792
Texas   2.195990  1.334959  1.350653
Oregon  0.969557  0.968748 -0.266218

In [125]:
 np.abs(frame)

b         d         e
Utah    1.156886  0.651762  0.476286
Ohio    1.461636  1.246607  0.008792
Texas   2.195990  1.334959  1.350653
Oregon  0.969557  0.968748  0.266218

# Lamda Function

In [126]:
f = lambda x: x*100
f(2)

200

In [131]:
f = lambda x: x.max() - x.min()

In [134]:
#apply() works on columns only and it only works for only frame not a particular value or index
frame.apply(f)

b    3.657625
d    2.581567
e    1.616871
dtype: float64