# Boolean Indexing

In [1]:
import numpy as np

In [2]:
names = np.array(['Mustafa', 'Jazzy', 'Haziq', 'Rafay', 'Hammad', 'Mehmood', 'Murtuza'])

In [3]:
data = np.random.randn(7,4)

In [4]:
names

array(['Mustafa', 'Jazzy', 'Haziq', 'Rafay', 'Hammad', 'Mehmood',
       'Murtuza'], dtype='<U7')

In [5]:
data

array([[ 2.21524538e-01,  1.13638467e+00,  2.53996378e-03,
        -1.12809829e+00],
       [-2.98463217e-01, -1.55786058e+00, -1.01100776e-01,
        -3.19704707e-01],
       [ 7.93778737e-01,  1.10114530e-01,  3.90056828e-01,
        -8.51574744e-01],
       [ 7.29567720e-01, -8.41983237e-01,  2.08632270e-01,
        -1.52765292e+00],
       [-2.06897266e-04,  3.28314606e-01,  9.97518725e-01,
        -4.90353795e-01],
       [-6.01832530e-01, -1.80525038e+00,  1.62779655e+00,
        -1.52667226e+00],
       [ 1.05762476e+00, -3.82975858e-01,  6.65279633e-01,
        -4.98327033e-01]])

In [6]:
names == 'Mustafa'

array([ True, False, False, False, False, False, False])

In [7]:
data[names == 'Mustafa']

array([[ 0.22152454,  1.13638467,  0.00253996, -1.12809829]])

In [8]:
data[names != 'Mustafa']

array([[-2.98463217e-01, -1.55786058e+00, -1.01100776e-01,
        -3.19704707e-01],
       [ 7.93778737e-01,  1.10114530e-01,  3.90056828e-01,
        -8.51574744e-01],
       [ 7.29567720e-01, -8.41983237e-01,  2.08632270e-01,
        -1.52765292e+00],
       [-2.06897266e-04,  3.28314606e-01,  9.97518725e-01,
        -4.90353795e-01],
       [-6.01832530e-01, -1.80525038e+00,  1.62779655e+00,
        -1.52667226e+00],
       [ 1.05762476e+00, -3.82975858e-01,  6.65279633e-01,
        -4.98327033e-01]])

In [9]:
data[names == 'Mustafa', 2:]

array([[ 0.00253996, -1.12809829]])

In [10]:
data

array([[ 2.21524538e-01,  1.13638467e+00,  2.53996378e-03,
        -1.12809829e+00],
       [-2.98463217e-01, -1.55786058e+00, -1.01100776e-01,
        -3.19704707e-01],
       [ 7.93778737e-01,  1.10114530e-01,  3.90056828e-01,
        -8.51574744e-01],
       [ 7.29567720e-01, -8.41983237e-01,  2.08632270e-01,
        -1.52765292e+00],
       [-2.06897266e-04,  3.28314606e-01,  9.97518725e-01,
        -4.90353795e-01],
       [-6.01832530e-01, -1.80525038e+00,  1.62779655e+00,
        -1.52667226e+00],
       [ 1.05762476e+00, -3.82975858e-01,  6.65279633e-01,
        -4.98327033e-01]])

In [11]:
data[names == 'Mustafa', 1:3]

array([[1.13638467, 0.00253996]])

In [12]:
data[3]

array([ 0.72956772, -0.84198324,  0.20863227, -1.52765292])

In [13]:
data[[3,4,0,1]]

array([[ 7.29567720e-01, -8.41983237e-01,  2.08632270e-01,
        -1.52765292e+00],
       [-2.06897266e-04,  3.28314606e-01,  9.97518725e-01,
        -4.90353795e-01],
       [ 2.21524538e-01,  1.13638467e+00,  2.53996378e-03,
        -1.12809829e+00],
       [-2.98463217e-01, -1.55786058e+00, -1.01100776e-01,
        -3.19704707e-01]])

In [14]:
data[~(names == 'Mustafa')]

array([[-2.98463217e-01, -1.55786058e+00, -1.01100776e-01,
        -3.19704707e-01],
       [ 7.93778737e-01,  1.10114530e-01,  3.90056828e-01,
        -8.51574744e-01],
       [ 7.29567720e-01, -8.41983237e-01,  2.08632270e-01,
        -1.52765292e+00],
       [-2.06897266e-04,  3.28314606e-01,  9.97518725e-01,
        -4.90353795e-01],
       [-6.01832530e-01, -1.80525038e+00,  1.62779655e+00,
        -1.52667226e+00],
       [ 1.05762476e+00, -3.82975858e-01,  6.65279633e-01,
        -4.98327033e-01]])

In [15]:
cond = names == 'Mustafa'

In [16]:
data[~cond]

array([[-2.98463217e-01, -1.55786058e+00, -1.01100776e-01,
        -3.19704707e-01],
       [ 7.93778737e-01,  1.10114530e-01,  3.90056828e-01,
        -8.51574744e-01],
       [ 7.29567720e-01, -8.41983237e-01,  2.08632270e-01,
        -1.52765292e+00],
       [-2.06897266e-04,  3.28314606e-01,  9.97518725e-01,
        -4.90353795e-01],
       [-6.01832530e-01, -1.80525038e+00,  1.62779655e+00,
        -1.52667226e+00],
       [ 1.05762476e+00, -3.82975858e-01,  6.65279633e-01,
        -4.98327033e-01]])

In [17]:
mask = (names == 'Mustafa') | (names == 'Haziq')

In [18]:
mask

array([ True, False,  True, False, False, False, False])

In [19]:
names

array(['Mustafa', 'Jazzy', 'Haziq', 'Rafay', 'Hammad', 'Mehmood',
       'Murtuza'], dtype='<U7')

In [20]:
data[mask]

array([[ 0.22152454,  1.13638467,  0.00253996, -1.12809829],
       [ 0.79377874,  0.11011453,  0.39005683, -0.85157474]])

In [21]:
data < 0

array([[False, False, False,  True],
       [ True,  True,  True,  True],
       [False, False, False,  True],
       [False,  True, False,  True],
       [ True, False, False,  True],
       [ True,  True, False,  True],
       [False,  True, False,  True]])

In [22]:
data[data < 0]

array([-1.12809829e+00, -2.98463217e-01, -1.55786058e+00, -1.01100776e-01,
       -3.19704707e-01, -8.51574744e-01, -8.41983237e-01, -1.52765292e+00,
       -2.06897266e-04, -4.90353795e-01, -6.01832530e-01, -1.80525038e+00,
       -1.52667226e+00, -3.82975858e-01, -4.98327033e-01])

In [23]:
data[data < 0] = 0

In [24]:
data

array([[0.22152454, 1.13638467, 0.00253996, 0.        ],
       [0.        , 0.        , 0.        , 0.        ],
       [0.79377874, 0.11011453, 0.39005683, 0.        ],
       [0.72956772, 0.        , 0.20863227, 0.        ],
       [0.        , 0.32831461, 0.99751872, 0.        ],
       [0.        , 0.        , 1.62779655, 0.        ],
       [1.05762476, 0.        , 0.66527963, 0.        ]])

# Fancy Indexing

In [36]:
arr = np.empty((8, 4))            
for i in range(8):
               arr[i] = i
        

In [37]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [38]:
arr[4]

array([4., 4., 4., 4.])

In [41]:
arr[[4,6]]

array([[4., 4., 4., 4.],
       [6., 6., 6., 6.]])

In [42]:
arr[[4,6],2:]

array([[4., 4.],
       [6., 6.]])

In [43]:
arr = np.arange(32).reshape((8,4))

In [44]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [45]:
arr[[1,5,7,2],[0,3,1,2]]

array([ 4, 23, 29, 10])

In [47]:
#1*0 , 1*3, 1*1, 1*2 
#5*0 , 5*3, 5*1, 5*2
#7*0 , 7*3, 7*1, 7*2
#2*0 , 2*3, 2*1, 2*2
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

# Transposing Arrays and Swapping Axes

In [48]:
arr = np.arange(15).reshape((3,5))

In [49]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [50]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])