In [23]:
a = [2,4,6,8,10]

In [24]:
b = []
for num in a:
    b.append(2*num)
b    

[4, 8, 12, 16, 20]

In [ ]:
import numpy as np

In [51]:
a = np.array( [1,2,3,4,5,6])

In [52]:
type(a)

numpy.ndarray

In [53]:
3*a

array([ 3,  6,  9, 12, 15, 18])

In [54]:
data1 = np.arange(10)
data1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
data1.ndim

1

matrix are tensor in machine learning 
vector 1dimension tensor hai

In [30]:
data.shape

(2, 3)

there are 2 rows
there are 3 columns

In [38]:
b= np.array([[100]])

In [39]:
b.ndim

2

No of bracket shows the dimensions

In [40]:
b.shape

(1, 1)

In [41]:
_3d = np.array([[[1,2,3],[4,5,6],[7,8,9]]])

In [42]:
_3d

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [43]:
threeD = np.arange(64).reshape(4,4,4)

In [44]:
threeD

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]],

       [[48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59],
        [60, 61, 62, 63]]])

In [47]:
threeD = np.arange(30).reshape(3,5,2) #3 is height or depth
threeD

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23],
        [24, 25],
        [26, 27],
        [28, 29]]])

In [46]:
threeD = np.arange(30).reshape(5,3,2)
threeD

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]],

       [[24, 25],
        [26, 27],
        [28, 29]]])

In [49]:
threeD.ndim

3

In [50]:
threeD = np.arange(30).reshape(2,5,3)
threeD

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]],

       [[15, 16, 17],
        [18, 19, 20],
        [21, 22, 23],
        [24, 25, 26],
        [27, 28, 29]]])

In [59]:
m1 = np.arange(12).reshape(4,3)
m2 = np.array([[1,2,3],[4,5,6],[7,8,9],[4,3,2]])

In [60]:
m1

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [61]:
m2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [4, 3, 2]])

In [62]:
m1.shape == m2.shape

True

In [63]:
m1+m2

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17],
       [13, 13, 13]])

In [64]:
m1-m2

array([[-1, -1, -1],
       [-1, -1, -1],
       [-1, -1, -1],
       [ 5,  7,  9]])

In [75]:
#shape same thatswhy il will multiply
m1*m2

array([[ 0,  2,  6],
       [12, 20, 30],
       [42, 56, 72],
       [36, 30, 22]])

In [76]:
m1/m2

array([[0.        , 0.5       , 0.66666667],
       [0.75      , 0.8       , 0.83333333],
       [0.85714286, 0.875     , 0.88888889],
       [2.25      , 3.33333333, 5.5       ]])

This is the element wise operation

In [77]:
m1.shape

(4, 3)

In [78]:
m2.shape

(4, 3)

In [79]:
m3 = np.arange(12).reshape(3,4)

In [80]:
m3.shape

(3, 4)

In [81]:
#multiplication but different shape
m1@m3

array([[ 20,  23,  26,  29],
       [ 56,  68,  80,  92],
       [ 92, 113, 134, 155],
       [128, 158, 188, 218]])

In [84]:
#function in numpy for multiplication
np.dot(m1,m3)

array([[ 20,  23,  26,  29],
       [ 56,  68,  80,  92],
       [ 92, 113, 134, 155],
       [128, 158, 188, 218]])

In [85]:
m1.dot(m3)

array([[ 20,  23,  26,  29],
       [ 56,  68,  80,  92],
       [ 92, 113, 134, 155],
       [128, 158, 188, 218]])

In [88]:
a = np.array([33.,44,66],dtype="float32")

In [89]:
a

array([33., 44., 66.], dtype=float32)

agr ek bh no float mai hogya to sare automatic float mai hojangy

In [90]:
a = np.array([33.,44,66],dtype=np.float32)

In [91]:
a

array([33., 44., 66.], dtype=float32)

In [92]:
b = np.asarray(a,np.int32)

In [93]:
b

array([33, 44, 66])

for changing data of an array

In [95]:
np.ones((10,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [98]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [99]:
np.empty(6)

array([2.12199579e-314, 6.36598737e-314, 1.06099790e-313, 1.48539705e-313,
       1.90979621e-313, 2.33419537e-313])

In [106]:
np.ones((3,4))*5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [109]:
m1 = np.full((3,4),7)
m1

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

In [110]:
m2 = np.ones_like(m1)

In [111]:
m2

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [112]:
alist = [1,2,3,4,5,6,7,8]
alist[4]

5

In [117]:
type(alist)

list

In [116]:
type(alist[2:4])

list

indexing kro to value ati ha
slicing kro to list ati ha

In [118]:
type(alist[4])

int

In [119]:
td = np.arange(36).reshape(6,6)

In [120]:
td

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [121]:
td[2,3] 

15

In [130]:
#td[r,c]
#td[--, --]
a = td[2:5,2:4]

In [131]:
a

array([[14, 15],
       [20, 21],
       [26, 27]])