# Boolean Indexing

In [78]:
import numpy as np

In [79]:
names = np.array(['Mustafa', 'Jazzy', 'Haziq', 'Rafay', 'Hammad', 'Mehmood', 'Murtuza'])

In [80]:
data = np.random.randn(7,4)

In [81]:
names

array(['Mustafa', 'Jazzy', 'Haziq', 'Rafay', 'Hammad', 'Mehmood',
       'Murtuza'], dtype='<U7')

In [82]:
data

array([[ 0.7692421 ,  0.21741333, -0.88906958, -0.23136217],
       [ 0.4893459 ,  0.64458372,  1.40628619,  0.3996003 ],
       [-0.97889   , -1.46739292, -0.7995322 ,  1.34983561],
       [-1.18546489, -0.6659628 ,  0.361242  ,  1.22012087],
       [ 1.34892714, -0.48498958, -1.84860292, -0.47864428],
       [ 1.25864277, -0.17470844,  0.74374086,  0.16266642],
       [ 0.35014583,  0.02451167,  0.89018995, -1.25691466]])

In [83]:
names == 'Mustafa'

array([ True, False, False, False, False, False, False])

In [84]:
data[names == 'Mustafa']

array([[ 0.7692421 ,  0.21741333, -0.88906958, -0.23136217]])

In [85]:
data[names != 'Mustafa']

array([[ 0.4893459 ,  0.64458372,  1.40628619,  0.3996003 ],
       [-0.97889   , -1.46739292, -0.7995322 ,  1.34983561],
       [-1.18546489, -0.6659628 ,  0.361242  ,  1.22012087],
       [ 1.34892714, -0.48498958, -1.84860292, -0.47864428],
       [ 1.25864277, -0.17470844,  0.74374086,  0.16266642],
       [ 0.35014583,  0.02451167,  0.89018995, -1.25691466]])

In [86]:
data[names == 'Mustafa', 2:]

array([[-0.88906958, -0.23136217]])

In [87]:
data

array([[ 0.7692421 ,  0.21741333, -0.88906958, -0.23136217],
       [ 0.4893459 ,  0.64458372,  1.40628619,  0.3996003 ],
       [-0.97889   , -1.46739292, -0.7995322 ,  1.34983561],
       [-1.18546489, -0.6659628 ,  0.361242  ,  1.22012087],
       [ 1.34892714, -0.48498958, -1.84860292, -0.47864428],
       [ 1.25864277, -0.17470844,  0.74374086,  0.16266642],
       [ 0.35014583,  0.02451167,  0.89018995, -1.25691466]])

In [88]:
data[names == 'Mustafa', 1:3]

array([[ 0.21741333, -0.88906958]])

In [89]:
data[3]

array([-1.18546489, -0.6659628 ,  0.361242  ,  1.22012087])

In [90]:
data[[3,4,0,1]]

array([[-1.18546489, -0.6659628 ,  0.361242  ,  1.22012087],
       [ 1.34892714, -0.48498958, -1.84860292, -0.47864428],
       [ 0.7692421 ,  0.21741333, -0.88906958, -0.23136217],
       [ 0.4893459 ,  0.64458372,  1.40628619,  0.3996003 ]])

In [91]:
data[~(names == 'Mustafa')]

array([[ 0.4893459 ,  0.64458372,  1.40628619,  0.3996003 ],
       [-0.97889   , -1.46739292, -0.7995322 ,  1.34983561],
       [-1.18546489, -0.6659628 ,  0.361242  ,  1.22012087],
       [ 1.34892714, -0.48498958, -1.84860292, -0.47864428],
       [ 1.25864277, -0.17470844,  0.74374086,  0.16266642],
       [ 0.35014583,  0.02451167,  0.89018995, -1.25691466]])

In [92]:
cond = names == 'Mustafa'

In [93]:
data[~cond]

array([[ 0.4893459 ,  0.64458372,  1.40628619,  0.3996003 ],
       [-0.97889   , -1.46739292, -0.7995322 ,  1.34983561],
       [-1.18546489, -0.6659628 ,  0.361242  ,  1.22012087],
       [ 1.34892714, -0.48498958, -1.84860292, -0.47864428],
       [ 1.25864277, -0.17470844,  0.74374086,  0.16266642],
       [ 0.35014583,  0.02451167,  0.89018995, -1.25691466]])

In [94]:
mask = (names == 'Mustafa') | (names == 'Haziq')

In [95]:
mask

array([ True, False,  True, False, False, False, False])

In [96]:
names

array(['Mustafa', 'Jazzy', 'Haziq', 'Rafay', 'Hammad', 'Mehmood',
       'Murtuza'], dtype='<U7')

In [97]:
data[mask]

array([[ 0.7692421 ,  0.21741333, -0.88906958, -0.23136217],
       [-0.97889   , -1.46739292, -0.7995322 ,  1.34983561]])

In [98]:
data < 0

array([[False, False,  True,  True],
       [False, False, False, False],
       [ True,  True,  True, False],
       [ True,  True, False, False],
       [False,  True,  True,  True],
       [False,  True, False, False],
       [False, False, False,  True]])

In [99]:
data[data < 0]

array([-0.88906958, -0.23136217, -0.97889   , -1.46739292, -0.7995322 ,
       -1.18546489, -0.6659628 , -0.48498958, -1.84860292, -0.47864428,
       -0.17470844, -1.25691466])

In [100]:
data[data < 0] = 0

In [101]:
data

array([[0.7692421 , 0.21741333, 0.        , 0.        ],
       [0.4893459 , 0.64458372, 1.40628619, 0.3996003 ],
       [0.        , 0.        , 0.        , 1.34983561],
       [0.        , 0.        , 0.361242  , 1.22012087],
       [1.34892714, 0.        , 0.        , 0.        ],
       [1.25864277, 0.        , 0.74374086, 0.16266642],
       [0.35014583, 0.02451167, 0.89018995, 0.        ]])

# Fancy Indexing

In [102]:
arr = np.empty((8, 4))            
for i in range(8):
               arr[i] = i
        

In [103]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [104]:
arr[4]

array([4., 4., 4., 4.])

In [105]:
arr[[4,6]]

array([[4., 4., 4., 4.],
       [6., 6., 6., 6.]])

In [106]:
arr[[4,6],2:]

array([[4., 4.],
       [6., 6.]])

In [107]:
arr = np.arange(32).reshape((8,4))

In [108]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [109]:
arr[[1,5,7,2],[0,3,1,2]]

array([ 4, 23, 29, 10])

In [110]:
#1*0 , 1*3, 1*1, 1*2 
#5*0 , 5*3, 5*1, 5*2
#7*0 , 7*3, 7*1, 7*2
#2*0 , 2*3, 2*1, 2*2
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

# Transposing Arrays and Swapping Axes

In [111]:
arr = np.arange(15).reshape((3,5))

In [112]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [113]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

# Universal Functions: Fast Element-Wise Array Functions

In [114]:
arr = np.random.randn(7) * 5

In [115]:
arr

array([ 1.22330525, -6.95192725,  3.01531554,  8.18493779, -3.63939224,
        4.51449305,  5.68977889])

In [116]:
remainder, whole_part = np.modf(arr)

In [117]:
remainder

array([ 0.22330525, -0.95192725,  0.01531554,  0.18493779, -0.63939224,
        0.51449305,  0.68977889])

In [118]:
whole_part

array([ 1., -6.,  3.,  8., -3.,  4.,  5.])

# Expressing Conditional Logic as Array Operations

In [119]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])

In [120]:
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])

In [121]:
cond = np.array([True, False, True, True, False])

In [122]:
result = [(x if c else y)
          for x, y, c in zip(xarr, yarr, cond)]

In [123]:
#if xarr True then print the value of xarr otherwise if prints yarr
result

[1.1, 2.2, 1.3, 1.4, 2.5]

In [124]:
#argmin is the function it returns the index of minimum values
#argmax is the function it returns the index of maximum values

In [125]:
 arr = np.arange(15).reshape((5, 3))

In [126]:
ravel = arr.ravel()

In [127]:
flatten = arr.flatten()

In [128]:
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [129]:
ravel

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [130]:
flatten

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [131]:
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [132]:
ravel[2:8] = 0

In [133]:
ravel

array([ 0,  1,  0,  0,  0,  0,  0,  0,  8,  9, 10, 11, 12, 13, 14])

In [134]:
arr

array([[ 0,  1,  0],
       [ 0,  0,  0],
       [ 0,  0,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [136]:
flatten[2:8] = 0

In [137]:
flatten

array([ 0,  1,  0,  0,  0,  0,  0,  0,  8,  9, 10, 11, 12, 13, 14])

In [138]:
arr

array([[ 0,  1,  0],
       [ 0,  0,  0],
       [ 0,  0,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

# Concatenating and Splitting Arrays

In [142]:
 arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [143]:
arr2 = np.array([[7, 8, 9], [10, 11, 12]])
arr2

array([[ 7,  8,  9],
       [10, 11, 12]])

In [144]:
np.concatenate([arr1,arr2])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [145]:
np.concatenate([arr1,arr2],axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [147]:
np.concatenate([arr1,arr2], axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [149]:
#vertical means expands column
np.vstack((arr1,arr2))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [153]:
#horizontal means expands row 
np.hstack((arr1,arr2))

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [155]:
splitt = np.arange(1,25).reshape(6,4)
splitt

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [161]:
np.vsplit(splitt,3)

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]), array([[ 9, 10, 11, 12],
        [13, 14, 15, 16]]), array([[17, 18, 19, 20],
        [21, 22, 23, 24]])]

In [162]:
np.hsplit(splitt,2)

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14],
        [17, 18],
        [21, 22]]), array([[ 3,  4],
        [ 7,  8],
        [11, 12],
        [15, 16],
        [19, 20],
        [23, 24]])]

# Repeating Elements: tile and repeat

In [165]:
arr = np.arange(3)

In [166]:
arr

array([0, 1, 2])

In [167]:
arr.repeat(3)

array([0, 0, 0, 1, 1, 1, 2, 2, 2])

In [168]:
np.tile(arr, 2)

array([0, 1, 2, 0, 1, 2])

In [169]:
arr

array([0, 1, 2])