# 3D-Array

In [ ]:
import numpy as np

In [10]:
arr3d = np.arange(50).reshape(2,5,5)
arr3d
#2 defines the depth of dimentsion(no of matrices)
#5 row
#5 column 

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]],

       [[25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]]])

In [11]:
arr3d[1,2,3]

38

In [12]:
arr3d[0,3,4]

19

In [13]:
arr3d[1,2:,1:3]

array([[36, 37],
       [41, 42],
       [46, 47]])

In [17]:
arr3d[0,2:,4:]
#2 dimension ki slicing hoto it returns 2d-array.

array([[14],
       [19],
       [24]])

In [20]:
arr3d[0,2:4,4]

array([14, 19])

In [21]:
arr3d[0:1,2:,4:]
#3no ki slicing starting ending di hoto it returns 3d-array.

array([[[14],
        [19],
        [24]]])

In [22]:
arr3d[0:1,2:,4]

array([[14, 19, 24]])

In [23]:
arr3d[0:,0:,0]

array([[ 0,  5, 10, 15, 20],
       [25, 30, 35, 40, 45]])

In [24]:
arr3d[0:,0:,0:1]

array([[[ 0],
        [ 5],
        [10],
        [15],
        [20]],

       [[25],
        [30],
        [35],
        [40],
        [45]]])